// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-08-01 17:22:57.27436043 +0700 +07 m=+0.093412266

package docs

import (
	"io/ioutil"

	"os"

	"github.com/swaggo/swag"
)

type s struct{}

func (s *s) ReadDoc() string {
	data, _ := ioutil.ReadFile(os.Getenv("GOPATH") + "/src/github.com/thuandoan274/auto-swagger/docs/swagger/swagger.yaml")
	return string(data)
}
func init() {
	swag.Register(swag.Name, &s{})
}
